# name: Release

# on:
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: "tag: git tag you want create. (sample 1.0.0)"
#         required: true
#       dry-run:
#         description: "dry-run: false = create release/nuget. true = never create release/nuget."
#         required: true
#         default: false
#         type: boolean

# env:
#   GIT_TAG: ${{ github.event.inputs.tag }}

# jobs:
#   update-version-number:
#     uses: ./.github/workflows/update-version-number.yaml
#     with:
#       tag: ${{ github.event.inputs.tag }}
#       dry-run: ${{ fromJson(github.event.inputs.dry-run) }}
   
#   create-release:
#     if: github.event.inputs.dry-run == 'false'    
#     needs: [update-version-number, build-dotnet]
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     timeout-minutes: 10
#     steps:
#     # Create Releases
#     - uses: softprops/action-gh-release@v1
#       id: create_release
#       with:
#         tag_name: ${{ env.GIT_TAG }}
#         name: v${{ env.GIT_TAG }}
#         draft: true
#         prerelease: false
#         generate_release_notes: true
